{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [07/May/2018 11:56:40] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/May/2018 11:56:41] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/May/2018 11:56:41] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/May/2018 11:56:41] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/May/2018 11:56:45] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/May/2018 11:56:47] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/May/2018 11:56:49] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [07/May/2018 11:56:51] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import dash\n",
    "from dash.dependencies import Input, Output\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "from pandas_datareader import data as web\n",
    "from datetime import datetime as dt\n",
    "import pandas_datareader \n",
    "import plotly \n",
    "import seaborn as sns\n",
    "import plotly.plotly as py\n",
    "import plotly.graph_objs as go\n",
    "\n",
    "daily_df = pd.read_csv(\"https://raw.githubusercontent.com/jdpersona/Dash_Apps/master/daily_df.csv\")\n",
    "\n",
    "app = dash.Dash()\n",
    "\n",
    "app.layout = html.Div(className='container', children=[\n",
    "    html.H1('NPS Changes Overtime'),\n",
    "    html.Hr(),\n",
    "    \n",
    "   html.Div(className='two columns', children=[ \n",
    "   dcc.Dropdown(id='items',\n",
    "     options=[\n",
    "        {'label': '30 Day', 'value': 30},\n",
    "        {'label': '60 Day', 'value': 60},\n",
    "        {'label': '90 Day', 'value': 90}\n",
    "        ],\n",
    "         value = 30\n",
    "         ), \n",
    "    ], style = {'width' : '28%'}),\n",
    "\n",
    "\n",
    "    html.Div( dcc.Graph(id='graph'), className='ten columns' )\n",
    "\n",
    "])\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "@app.callback(Output('graph', 'figure'), [Input('items', 'value')])    \n",
    "def update_graph(items):\n",
    "    window1 = daily_df.rolling(items).sum().dropna()\n",
    "   # Compute NPS\n",
    "    window1['total'] = window1.detractors + window1.passives + window1.promoters\n",
    "    window1['NPS'] = 100*((window1.promoters/window1.total) - (window1.detractors/window1.total))\n",
    "    window1['DetPct'] = window1.detractors/window1.total\n",
    "    window1['ProPct'] = window1.promoters/window1.total\n",
    "    window1['SE_NPS'] = 100*np.sqrt((window1.ProPct*(1-window1.ProPct) + window1.DetPct*(1-window1.DetPct) + 2*window1.ProPct*window1.DetPct)/window1.total)                 \n",
    "    window1['MoE'] = 1.96*window1.SE_NPS\n",
    "    window1['NPS_low'] = window1.NPS - window1.MoE\n",
    "    window1['NPS_high'] = window1.NPS + window1.MoE\n",
    "  # Plot 10-day NPS with MoE boundaries\\\n",
    "   # Lists to use in plot\n",
    "    NPS = list(window1.NPS)\n",
    "    NPS_low = list(window1.NPS_low)\n",
    "    NPS_high = list(window1.NPS_high)\n",
    "    \n",
    "    upper_bound = go.Scatter(\n",
    "        name='Upper Bound',\n",
    "        x=window1.date,\n",
    "        y=window1.NPS_high,\n",
    "        mode='lines',\n",
    "        marker=dict(color=\"444\"),\n",
    "        line=dict(width=0),\n",
    "        fillcolor='rgba(68, 68, 68, 0.3)',\n",
    "        fill='tonexty' )\n",
    "\n",
    "    trace = go.Scatter(\n",
    "      name='Measurement',\n",
    "      x=window1.date,\n",
    "      y=window1.NPS,\n",
    "      mode='lines',\n",
    "      line=dict(color='rgb(31, 119, 180)'),\n",
    "      fillcolor='rgba(68, 68, 68, 0.3)',\n",
    "      fill='tonexty')\n",
    "    \n",
    "    \n",
    "    lower_bound = go.Scatter(\n",
    "     name='Lower Bound',\n",
    "     x=window1.date,\n",
    "     y=window1.NPS_low,\n",
    "     marker=dict(color=\"444\"),\n",
    "     line=dict(width=0),\n",
    "     mode='lines' )\n",
    "\n",
    "    # Trace order can be important\n",
    "      # with continuous error bars\n",
    "    data = [lower_bound, trace, upper_bound]\n",
    "\n",
    "    return {\n",
    "        'data': data,\n",
    "        'layout': go.Layout(\n",
    "            yaxis={'title': 'Daily NPS Score'},\n",
    "            margin={'l': 40, 'b': 40, 't': 10, 'r': 10}\n",
    "            )\n",
    "\n",
    "            }\n",
    "\n",
    "app.css.append_css({'external_url': 'https://codepen.io/chriddyp/pen/dZVMbK.css'})\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run_server()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
